source 'https://rubygems.org'
git_source(:github) { |repo| "https://github.com/#{repo}.git" }

gem 'rails', '~> 6.1.7.4'
gem 'pg'
gem 'sass-rails', '~> 5.0', '>= 5.0.8'
gem 'uglifier', '>= 1.3.0'
gem 'coffee-rails', '~> 5.0', '>= 5.0.0'
gem 'jbuilder', '~> 2.5'
gem 'bootsnap', '>= 1.1.0', require: false
gem "settingslogic"
gem 'jwt'
gem 'rest-client'

# Assets
gem 'slim'
gem 'autoprefixer-rails'
gem 'bootstrap', '~> 4.4.1'
gem 'jquery-rails', '>= 4.3.4'

group :development, :test do
  gem 'pry'
end

group :development do
  gem 'web-console', '>= 4.0.0'
  gem 'listen', '>= 3.0.5', '< 3.2'
  gem 'spring'
  gem 'spring-watcher-listen', '~> 2.0.0'
  gem "better_errors"
end

group :test do
  gem 'rspec'
  gem 'rspec-rails', '>= 3.8.3'
  gem 'database_cleaner'
  gem 'factory_bot_rails', '>= 4.10.0'
  gem 'chromedriver-helper'
  gem 'capybara-selenium'
  gem 'capybara-screenshot', require: false
  gem 'rails-controller-testing', '>= 1.0.5'
end
