source 'https://rubygems.org'
git_source(:github) { |repo| "https://github.com/#{repo}.git" }

gem 'rails', '~> 5.2.4.5'
gem 'pg'
gem 'sass-rails', '~> 5.0', '>= 5.0.7'
gem 'uglifier', '>= 1.3.0'
gem 'coffee-rails', '~> 4.2', '>= 4.2.2'
gem 'jbuilder', '~> 2.5'
gem 'bootsnap', '>= 1.1.0', require: false
gem "settingslogic"
gem 'jwt'
gem 'rest-client'

# Assets
gem 'slim'
gem 'autoprefixer-rails'
gem 'bootstrap', '~> 4.3.1'
gem 'jquery-rails', '>= 4.3.3'

group :development, :test do
  gem 'pry'
end

group :development do
  gem 'web-console', '>= 3.7.0'
  gem 'listen', '>= 3.0.5', '< 3.2'
  gem 'spring'
  gem 'spring-watcher-listen', '~> 2.0.0'
  gem "better_errors"
end

group :test do
  gem 'rspec'
  gem 'rspec-rails', '>= 3.8.2'
  gem 'database_cleaner'
  gem 'factory_bot_rails', '>= 4.8.2'
  gem 'chromedriver-helper', '>= 2.1.0'
  gem 'capybara-selenium', '>= 0.0.6'
  gem 'capybara-screenshot', '>= 1.0.22', require: false
  gem 'rails-controller-testing', '>= 1.0.4'
end
